# Generated by Django 2.2.5 on 2019-10-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('ranking', models.FloatField(default=0)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.League')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Char')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.League')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenging_score', models.IntegerField(default=0)),
                ('rival_score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('replay_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('ranking_del_challenging', models.FloatField(default=0)),
                ('ranking_del_rival', models.FloatField(default=0)),
                ('challenging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenging', to='app.Player')),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.League')),
                ('loser_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_player', to='app.Player')),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MatchType')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival', to='app.Player')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tournament')),
                ('victory_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victory_player', to='app.Player')),
            ],
        ),
        migrations.AddField(
            model_name='char',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
        ),
    ]
