# Generated by Django 2.2.1 on 2019-05-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ordinal', models.CharField(blank=True, max_length=255)),
                ('position', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplaintType')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('org_address', models.CharField(max_length=255)),
                ('org_lat', models.CharField(max_length=255)),
                ('org_lng', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplaintCategory')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comuna')),
                ('ttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ComplaintType')),
            ],
        ),
    ]
