# Generated by Django 2.2.5 on 2019-12-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url_image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Char'),
            preserve_default=False,
        ),
    ]
