# Generated by Django 2.2.1 on 2019-05-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintcategory',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='complainttype',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='slug',
            new_name='url',
        ),
    ]
