# Generated by Django 2.2.5 on 2019-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='ranking_del',
            new_name='ranking_del_challenging',
        ),
        migrations.AddField(
            model_name='result',
            name='ranking_del_rival',
            field=models.FloatField(default=0),
        ),
    ]
