# Generated by Django 2.2.1 on 2019-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190514_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='votes_agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='votes_disagree',
            field=models.IntegerField(default=0),
        ),
    ]
