# Generated by Django 2.2.1 on 2019-10-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191004_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
        ),
        migrations.AlterField(
            model_name='league',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
        ),
    ]
