# Generated by Django 2.2.5 on 2019-12-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191204_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='description',
        ),
    ]
