# Generated by Django 2.2.1 on 2019-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190515_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='has_voted',
            field=models.BooleanField(default=0),
        ),
    ]
