# Generated by Django 2.2.1 on 2019-10-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191004_0223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.League'),
        ),
        migrations.AddField(
            model_name='result',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.League'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.League'),
        ),
    ]
