# Generated by Django 2.2.5 on 2019-12-10 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20191210_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
