# Generated by Django 2.2.1 on 2019-05-15 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_complaint_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
