# Generated by Django 2.2.1 on 2019-10-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191004_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='player',
            name='url_image',
        ),
        migrations.AlterField(
            model_name='char',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
