# Generated by Django 2.2.1 on 2019-10-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191006_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='online',
        ),
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='sdfds', unique=True),
            preserve_default=False,
        ),
    ]
