# Generated by Django 2.2.1 on 2019-05-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190515_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='create',
            new_name='created',
        ),
    ]
