# Generated by Django 2.2.5 on 2019-12-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_league_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('nickname', 'league')},
        ),
    ]
