# Generated by Django 2.2.5 on 2019-12-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_medal_medaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
