# Generated by Django 2.2.1 on 2019-05-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190515_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
