# Generated by Django 2.2.1 on 2019-05-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_complaint_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ttype',
        ),
        migrations.RemoveField(
            model_name='complaintcategory',
            name='ttype',
        ),
        migrations.DeleteModel(
            name='ComplaintType',
        ),
    ]
