# Generated by Django 2.2.1 on 2019-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190516_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcategory',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
