# Generated by Django 2.2.1 on 2019-05-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_complaintcategory_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(default='sdfsdf'),
            preserve_default=False,
        ),
    ]
