# Generated by Django 2.2.1 on 2019-05-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_complaint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
