# Generated by Django 2.2.1 on 2019-08-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190813_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tournament'),
        ),
    ]
