# Generated by Django 2.2.1 on 2019-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_results_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
