# Generated by Django 2.2.1 on 2019-08-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
