# Generated by Django 2.2.1 on 2019-08-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_player_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
    ]
