# Generated by Django 2.2.1 on 2019-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190813_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='url_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
