# Generated by Django 2.2.1 on 2019-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_char_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='url_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
