# Generated by Django 2.2.5 on 2019-09-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_results_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintCategory',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
