# Generated by Django 2.2.5 on 2019-09-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190926_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='results',
            name='level',
        ),
        migrations.RemoveField(
            model_name='results',
            name='online',
        ),
    ]
