# Generated by Django 2.2.5 on 2019-09-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_results_replay_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='ranking_del',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
