# Generated by Django 2.2.5 on 2019-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190926_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
