# Generated by Django 2.2.5 on 2019-09-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190926_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='loser_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loser_player', to='app.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='victory_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victory_player', to='app.Player'),
        ),
    ]
