# Generated by Django 2.2.5 on 2019-09-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190927_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='loser_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_player', to='app.Player'),
        ),
        migrations.AlterField(
            model_name='result',
            name='victory_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victory_player', to='app.Player'),
        ),
    ]
